[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501
maxUploadSize = 200
maxMessageSize = 200
fileWatcherType = "poll"

[runner]
fastReruns = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
